sudo: required
language: node_js
node_js:
  - 10
services:
  - docker

cache:
  directories:
  - ~/google-cloud-sdk

before_install:
  - ./scripts/install.sh

install:
  - lerna bootstrap --ci

script:
  - lerna run test

deploy:
- provider: script
  skip_cleanup: true
  script: ./scripts/deploy.sh
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: ./scripts/deploy.sh
  on:
    branch: beta