apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: 'API_CLIENT_WS'
              valueFrom:
                configMapKeyRef:
                  name: {{ template "app.fullname" . }}
                  key: apiClientWs
            - name: 'API_CLIENT_HTTP'
              valueFrom:
                configMapKeyRef:
                  name: {{ template "app.fullname" . }}
                  key: apiClientHttp
            - name: 'AUTH0_REDIRECT_URI'
              valueFrom:
                configMapKeyRef:
                  name: {{ template "app.fullname" . }}
                  key: auth0RedirectUri
            - name: 'AUTH0_CLIENT_ID'
              valueFrom:
                secretKeyRef:
                  name: {{ template "app.fullname" . }}
                  key: auth0ClientId
            - name: 'AUTH0_CLIENT_SECRET'
              valueFrom:
                secretKeyRef:
                  name: {{ template "app.fullname" . }}
                  key: auth0ClientSecret
            - name: 'APP_KEY'
              valueFrom:
                secretKeyRef:
                  name: {{ template "app.fullname" . }}
                  key: appKey
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
