
port:
  __format: 'json'
  __name: PORT

auth0:
  clientId: AUTH0_CLIENT_ID
  clientSecret: AUTH0_CLIENT_SECRET
  redirectUri: AUTH0_REDIRECT_URI

key: APP_KEY

api:
  client:
    http: API_CLIENT_HTTP
    ws: API_CLIENT_WS
