mongo:
  url: mongodb://mongo-mongodb:27017/ureka

port: 3000

api:
  server:
    http: http://localhost:3000
  client:
    http: https://app.ureka.io
    ws: wss://app.ureka.io


auth0:
  redirectUri: https://app.ureka.io/auth/callback

redis:
  host: redis-master
